version: '3.1'
services:
  mongo:
    image: mongo
    command: --serviceExecutor adaptive
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my@m0ng0
    volumes:
        [
            C:\Users\Victor\PycharmProjects\Git\Geekbrains\Methods-of-collecting-and-processing-data\Lesson03\mongodb:/data/db
        ]
        
    ports:
        [
            27017:27017
        ]